[package]
name = "tauri-plugin-printer"
version = "2.0.0"
authors = ["Alfian Lensun <alfianlensundev@gmail.com>"]
description = "Tauri V2 Plugin for printer access"
edition = "2021"
homepage = "https://crates.io/crates/tauri-plugin-printer"
readme = "README.md"
rust-version = "1.77.2"
exclude = ["/examples", "/webview-dist", "/webview-src", "/node_modules"]
links = "tauri-plugin-printer"
keywords = [
    "tauri",
    "printer",
    "print",
    "printing",
    "json"
]
categories = [
    "os",
    "os::windows-apis"
]
license = "MIT"
repository = "https://github.com/alfianlensundev/tauri-plugin-printer"


[dependencies]
tauri = { version = "2.0.6" }
serde = "1.0"
serde_json = "1.0.128"
serde_with = "3.11.0"
thiserror = "1.0"
tokio = { version = "1.41.0", features = ["macros", "rt"] }

[build-dependencies]
tauri-plugin = { version = "2.0.1", features = ["build"] }
